service: serverless-guru-challenge
configValidationMode: error
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: default
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

functions:
  getStudents:
    handler: handler.getStudents
  getStudent:
    handler: handler.getStudent
  addStudent:
    handler: handler.addStudent
  updateStudentScore:
    handler: handler.updateStudentScore
  deleteStudent:
    handler: handler.deleteStudent

custom:
  stages:
    - dev
    - prod
  output: 
    file: ./front/src/stack.json

resources:
  Resources:
    StudentDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "name"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "name"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 4
          WriteCapacityUnits: 4
        TableName: Student

    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: appsync-lambda
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: lambda:invokeFunction
                  Resource:
                    - !GetAtt GetStudentLambdaFunction.Arn
                    - !Join [ "", [ !GetAtt GetStudentLambdaFunction.Arn, "*" ] ]
                    - !GetAtt GetStudentsLambdaFunction.Arn
                    - !Join [ "", [ !GetAtt GetStudentsLambdaFunction.Arn, "*" ] ]
                    - !GetAtt AddStudentLambdaFunction.Arn
                    - !Join [ "", [ !GetAtt AddStudentLambdaFunction.Arn, "*" ] ]
                    - !GetAtt UpdateStudentScoreLambdaFunction.Arn
                    - !Join [ "", [ !GetAtt UpdateStudentScoreLambdaFunction.Arn, "*" ] ]
                    - !GetAtt DeleteStudentLambdaFunction.Arn
                    - !Join [ "", [ !GetAtt DeleteStudentLambdaFunction.Arn, "*" ] ]

    GetStudentsLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt GetStudentsLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: !Join ["", ["logs.", !Ref AWS::Region, ".amazonaws.com" ] ]

    GetStudentLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt GetStudentLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: !Join ["", ["logs.", !Ref AWS::Region, ".amazonaws.com" ] ]
    
    AddStudentLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt AddStudentLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: !Join ["", ["logs.", !Ref AWS::Region, ".amazonaws.com" ] ]

    UpdateStudentScoreLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt UpdateStudentScoreLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: !Join ["", ["logs.", !Ref AWS::Region, ".amazonaws.com" ] ]

    DeleteStudentLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt DeleteStudentLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: !Join ["", ["logs.", !Ref AWS::Region, ".amazonaws.com" ] ]


    AppSyncApi:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        AuthenticationType: "API_KEY"
        Name: ${self:service}-${opt:stage,'dev'}


    AppSyncAPIKey:
      Type: AWS::AppSync::ApiKey
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId


    AppSyncSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        Definition: ${file(./schema.graphql)}


    GetStudentLambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Type: AWS_LAMBDA
        Name: getStudentDS_${opt:stage,'dev'}
        ApiId: !GetAtt AppSyncApi.ApiId
        ServiceRoleArn: !GetAtt LambdaRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetStudentLambdaFunction.Arn


    GetStudentQueryResolver:
      Type: AWS::AppSync::Resolver
      DependsOn: AppSyncSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        TypeName: Query
        FieldName: getStudent
        DataSourceName: !GetAtt GetStudentLambdaDataSource.Name
    

    GetStudentsLambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Type: AWS_LAMBDA
        Name: getStudentsDS_${opt:stage,'dev'}
        ApiId: !GetAtt AppSyncApi.ApiId
        ServiceRoleArn: !GetAtt LambdaRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetStudentsLambdaFunction.Arn

    GetStudentsQueryResolver:
      Type: AWS::AppSync::Resolver
      DependsOn: AppSyncSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        TypeName: Query
        FieldName: getStudents
        DataSourceName: !GetAtt GetStudentsLambdaDataSource.Name
    
    UpdateStudentScoreLambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Type: AWS_LAMBDA
        Name: updateStudentDS_${opt:stage,'dev'}
        ApiId: !GetAtt AppSyncApi.ApiId
        ServiceRoleArn: !GetAtt LambdaRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt UpdateStudentScoreLambdaFunction.Arn


    UpdateStudentScoreQueryResolver:
      Type: AWS::AppSync::Resolver
      DependsOn: AppSyncSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        TypeName: Mutation
        FieldName: updateStudentScore
        DataSourceName: !GetAtt UpdateStudentScoreLambdaDataSource.Name

    AddStudentLambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Type: AWS_LAMBDA
        Name: addStudentDS_${opt:stage,'dev'}
        ApiId: !GetAtt AppSyncApi.ApiId
        ServiceRoleArn: !GetAtt LambdaRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt AddStudentLambdaFunction.Arn


    AddStudentQueryResolver:
      Type: AWS::AppSync::Resolver
      DependsOn: AppSyncSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        TypeName: Mutation
        FieldName: addStudent
        DataSourceName: !GetAtt AddStudentLambdaDataSource.Name

    DeleteStudentLambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Type: AWS_LAMBDA
        Name: deleteStudentDS_${opt:stage,'dev'}
        ApiId: !GetAtt AppSyncApi.ApiId
        ServiceRoleArn: !GetAtt LambdaRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt DeleteStudentLambdaFunction.Arn

    DeleteStudentQueryResolver:
      Type: AWS::AppSync::Resolver
      DependsOn: AppSyncSchema
      Properties:
        ApiId: !GetAtt AppSyncApi.ApiId
        TypeName: Mutation
        FieldName: deleteStudent
        DataSourceName: !GetAtt DeleteStudentLambdaDataSource.Name
        
  Outputs:
    AppSyncAPIKey:
      Description: The AppSync API Key used for authorizing users making GraphQL invocations.
      Value: !GetAtt AppSyncAPIKey.ApiKey
    GraphQLApiEndpoint:
      Description: The URL to the GraphQL Endpoint
      Value: !GetAtt AppSyncApi.GraphQLUrl
    GraphQLApiId:
      Description: The API ID of the GraphQL API
      Value: !GetAtt AppSyncApi.ApiId

package:
  patterns:
    -'!.git/**'